### ISSUE TITLE
Allow use conditional directives at least within the section of the import/export directives

### ISSUE THREAD

**Issue by mezoni** [dart-lang/dart_enhancement_proposals#10]
```dart
// Directives import/export
// Here allowed conditional directives

// Declarations
// Here not allowed conditional directives
```

```dart
library name

#if env_var == constant expression
// Directives import/export
#elif env_var == constant expression
// Directives import/export
#else
// Directives import/export
#endif
```

```dart
library name

#if dart_platform == "server" || dart_platform == "browser"
import "common.dart";
#else
#error Unsupported platform
#endif

#if dart_platform == "server"
import "server.dart";
#elif  dart_platform == "browser"
import "browser.dart";
#else
#error Unsupported platform
#endif
```

**Comment by a14n** [comment]
It looks like #6.

**Comment by mezoni** [comment]
This is issue for it but I cannot understand "why was chosen github issue per proposal?"
I not expected that was looks like the new proposal.
I.e. github issue means a proposal?
But where discuss about the proposal and place issues for proposal?
Int he body of issue (proposal)?

**Comment by jmesserly** [comment]
please file this issue on the tracker for the proposal: https://github.com/lrhn/dep-configured-imports/issues

**Comment by munificent** [comment]
> I.e. github issue means a proposal?

The GitHub issue here tracks the *status* of a proposal. Each proposal has its own repo.

**Comment by mezoni** [comment]
Thank you.
I already understood.
I was not expected that Dart Team will use github for this purpose instead of the "write in the Dart language special web application for this purpose" as the way to show that this is possible with current features that currently are available for Dart platform.
