### ISSUE TITLE
Where to place dart_enhancement_proposals

### ISSUE THREAD

**Issue by mezoni** [dart-lang/dart_enhancement_proposals#11]
If I create here new issue (as it expected on the github) then it looks like a new proposal.
I have questions:
- Where to place the issues on the existing proposals?
- Where to place issues on whole `dart_enhancement_proposals`?

**Comment by jmesserly** [comment]
> Where to place the issues on the existing proposals?

on the proposal's issue tracker

> Where to place issues on whole dart_enhancement_proposals?

here.
