### ISSUE TITLE
dynamic load of classes at runtime

### ISSUE THREAD

**Issue by dam0vm3nt** [dart-lang/dart_enhancement_proposals#12]
Adding the possibility to dynamically load a class without having to know it at build time (dart2js).

**Comment by munificent** [comment]
Hi. This is a valid feature request, but it's not a concrete proposal. If you'd like to discuss the general idea of dynamic loading, the best way to do that is on the [core-dev](https://groups.google.com/a/dartlang.org/forum/#!forum/core-dev) mailing list. From there, you can work towards building up a concrete proposal that can eventually work its way back here.

**Comment by sethladd** [comment]
For my own make better learnings, it sounds like the advice is not to open a feature bug on dartbug.com but instead start a thread on core-dev ?

**Comment by munificent** [comment]
Yup!

**Comment by mezoni** [comment]
This can be implented by the suppiled "native library".
For "dart2js" in javascript language.
For "dartvm" in "patch classes".
For "dev_compiler" in javascript language.
This looks like the proposal for extending Dart SDK.

**Comment by dam0vm3nt** [comment]
understood. thank for the advice.
There was already an  open issue with a long discussion about this point, that eventually was migrated to the new issue tracking system.
It is : 

https://code.google.com/p/dart/issues/detail?id=10530

I thought this was a better place to report the same thing, but eventually I was wrong.

**Comment by mezoni** [comment]
>> I thought this was a better place to report the same thing, but eventually I was wrong.

Sometimes the problems are not in the absence of the good proposal.
This place is a right place for proposals but not for request of features.
And, as I say, problems are not in the absence of the good proposal but problem in the impossibility to implement some ideas in the appropriate time.
That is:
- Request does not means a proposal.
- Accepted request does not means acceptance to implement it.
- Proposal does not means that it should be accepted (with the exception of those that were was proposed by the Dart team:-)
- Absence of the proposal does not means it cannot be implemented only by the request.

You choose for it itself what is much appropriate for you.
