### ISSUE TITLE
Keep proposal in a separate repo after acceptance

### ISSUE THREAD

**Issue by seaneagan** [dart-lang/dart_enhancement_proposals#18]
After a proposal is accepted it is still useful to file issues against it.  For example, I just filed #17.  It might be easier to manage issues if the DEPs remained in a separate repo after acceptance.  These could be forks of the original repos in a `tc52` github organization.  This repo could then have a list of linked accepted proposals.

**Comment by munificent** [comment]
> After a proposal is accepted it is still useful to file issues against it.

I'm actually not sure how useful it is, in practice. Once it's been accepted, it's going to TC 52 and hopefully into the language spec. At that point, it's carved in stone. This is why it's so important to get lots of good feedback *before* it gets accepted.

> These could be forks of the original repos in a tc52 github organization.

I suppose we could do something like that, but I fear it's too much of a headache to maintain. It would certainly be nice to be able to bang on proposals even after acceptance, but I think the reality is that when a proposal is accepted, its ship has sailed.

If you want to modify it then, I think you basically have to create a new proposal. :confused:

**Comment by seaneagan** [comment]
Oh, I was under the impression that TC 52 would take proposals accepted by the DEP comittee and iterate upon them until they are happy.  If so, it would be nice if this iteration happened "in the open", just like the DEP iteration.

**Comment by munificent** [comment]
> I was under the impression that TC 52 would take proposals accepted by the DEP comittee and iterate upon them until they are happy. 

That's right, though our hope is that by the time a proposal goes to TC52 that it will need few changes.

> If so, it would be nice if this iteration happened "in the open", just like the DEP iteration.

I think they plan to publish notes from their meetings, but I don't think it will be as iterative or collaborative as the DEP process. When a proposal gets shipped to TC52, I consider it "done" in that I (and other people not on TC52) basically don't have any more say into what happens to it.
