### ISSUE TITLE
Configured imports (simplification)

### ISSUE THREAD

**Issue by eernstg** [dart-lang/dart_enhancement_proposals#19]
I have created a slight [variant of Lasse's proposal for configurable import statements][confimp], simplifying the static analysis.  The main idea is that only top-level functions can be imported, and they have type annotations in the import directive.

[confimp]: https://github.com/eernstg/dep-configured-imports

**Note: This issue exists to track the status of the proposal. If you would like to provide feedback on the proposal itself, please do so on its repo, linked above.**

**Comment by nex3** [comment]
Aren't we supposed to wait to post proposals here until they have broad community support?

**Comment by nex3** [comment]
Also, should this maybe be done as a pull request for Lasse's proposal, since it's so similar?

**Comment by munificent** [comment]
> Aren't we supposed to wait to post proposals here until they have broad community support?

It's basically up to the author to decide when they want the community to look at it, though it gets a bit muddy when the author is on the committee. :)

I labeled it a "draft" to try to reflect that Erik put this "out there", but I'm not sure if it's really ready for a thumbs up/down.

**Comment by eernstg** [comment]
I proposed that, Lasse proposed to create the fork.  We agreed that a merge
might happen later.

On Fri, Mar 13, 2015 at 9:03 PM, Natalie Weizenbaum <
notifications@github.com> wrote:

> Also, should this maybe be done as a pull request for Lasse's proposal,
> since it's so similar?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dart-lang/dart_enhancement_proposals/issues/19#issuecomment-79320903>
> .
>



-- 
Erik Ernst  -  Google Danmark ApS
Skt Petri Passage 5, 2 sal, 1165 København K, Denmark
CVR no. 28866984

**Comment by mezoni** [comment]
>> I proposed that, Lasse proposed to create the fork. 

That is, Lasse does not allow to propose modifications to its DEP?
Only create fork is one possible way?
I now begin understand why there I cannot find community but I can find only developers and a few other person which have no chance to change something.

>> I proposed that, Lasse proposed to create the fork. 

You can only do what allow for you the developers?

**Comment by eernstg** [comment]
On Sat, Mar 14, 2015 at 8:52 AM, mezoni <notifications@github.com> wrote:

>  I proposed that, Lasse proposed to create the fork.
>
>  That is, Lasse does not allow to propose modifications to its DEP?
>
We didn't discuss alternatives such as a pull request in detail, but it
seemed more open-minded to create a fork such that the two proposals
(Lasse's, and my-variant-based-on-Lasse's) could coexist.  They can always
be merged if that turns out to be useful.

> Only create fork is one possible way?
> I now begin understand why there I cannot find community but I can find
> only developers and a few other person which have no chance to change
> something.
>
But anyone who wants to create a fork of a publically available github
repository can do that, so how could that technique block anyone?

>  I proposed that, Lasse proposed to create the fork.
>
>  You can only do what allow for you the developers?
>
Of course, Lasse's repository https://github.com/lrhn/dep-configured-imports
is handled in the way he likes, just like any other proposal provided in a
repository owned by somebody else.  But the point is that it could be
counter-productive to use a pull request.  If Lasse's proposal needs to
develop, and mine too, then they can do that when they exist separately,
but if I had submitted a pull request then the two couldn't coexist.

  best regards,

-- 
Erik Ernst  -  Google Danmark ApS
Skt Petri Passage 5, 2 sal, 1165 København K, Denmark
CVR no. 28866984

**Comment by mezoni** [comment]
@eernstg 

I always thought that  the before the proposal wil be accepted (accepted to work), it are remains in some state were proposed (and was made) modifications on this proposal considered as the revisions of specification.

>> But the point is that it could be counter-productive to use a pull request. 

I don't think so.
It is very productive at beginning to discuss but if this is not a productive by some reason or everything is deadlocked then possible there exists only one solution to break the deadlock is to create a small variative proposal.

**Comment by eernstg** [comment]
Proposals will always potentially be modified during the DEP process, but I
didn't want to suggest that my change should block any of the other
potential further developments that Lasse might want to explore, so I felt
that it would be inappropriate to use a pull request. That's what I just
meant when I wrote 'counter-productive'.

On Mon, Mar 16, 2015 at 1:25 PM, mezoni <notifications@github.com> wrote:

> @eernstg <https://github.com/eernstg>
>
> I always thought that the before the proposal wil be accepted (accepted to
> work), it are remains in some state were proposed (and was made)
> modifications on this proposal considered as the revisions of specification.
>
>  But the point is that it could be counter-productive to use a pull
> request.
>
>  I don't think so.
> It is very productive at beginning to discuss but if this is not a
> productive by some reason or everything is deadlocked then possible there
> exists only one solution to break the deadlock is to create a small
> variative proposal.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dart-lang/dart_enhancement_proposals/issues/19#issuecomment-81617761>
> .
>



-- 
Erik Ernst  -  Google Danmark ApS
Skt Petri Passage 5, 2 sal, 1165 København K, Denmark
CVR no. 28866984

**Comment by mezoni** [comment]
@eernstg 

Maybe, maybe...	
JSR (Java Specification Requests) also duplicates one another?
Of course, I know that Dart is not a Java...

**Comment by eernstg** [comment]
I haven't been sufficiently involved in the JSR processes to know how they
handled variants of proposals and possible merging, but similar issues
would presumably come up naturally in any context where different people
create variant proposals.  I think it will work OK with the fork approach.

On Mon, Mar 16, 2015 at 2:28 PM, mezoni <notifications@github.com> wrote:

> @eernstg <https://github.com/eernstg>
>
> Maybe, maybe...
> JSR (Java Specification Requests) also duplicates one another?
> Of course, I know that Dart is not a Java...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dart-lang/dart_enhancement_proposals/issues/19#issuecomment-81664627>
> .
>



-- 
Erik Ernst  -  Google Danmark ApS
Skt Petri Passage 5, 2 sal, 1165 København K, Denmark
CVR no. 28866984

**Comment by munificent** [comment]
It's been a while since this DEP was updated! As you probably know, we're moving ahead on interface libraries (#40), so I'm closing this alternate approach, though many of the ideas of it made their way into #40.
