### ISSUE TITLE
Anyone can create and champion a DEP, but this does not mean that Dart is a democracy. 

### ISSUE THREAD

**Issue by mezoni** [dart-lang/dart_enhancement_proposals#21]
The words `Anyone can create and champion a DEP, but this does not mean that Dart is a democracy` from the `README.md`.

That's explain a lot but I don't think that this is a correct formulation of the answer on the question "So anyone can change Dart?"

I think that, if the DEP committee wants to remain this formulation as the main principle of the DEP, then committee should at least divide this formulation on two part and place them in different sentences.

As for me, the words "long and laborious process" is better than "does not mean that Dart is a democracy".

If there is no "democracy" does not means this that there exists only the "monocracy"?

I understand that `DEPs are managed by the DEP committee`.
But I cannot understand what means a `DEP management` in the context with the `not mean is a democracy`?

What  means `DEPs are managed by the DEP committee`:
- Dart-Enhancement-Proposals are managed by the DEP committee
- Dart-Enhancement-Proposals process are managed by the DEP committee

Both formulations looks similar but they are different.
I agree that `DEP process are managed by the DEP committee`.
But I cannot agree that `DEP are managed by the DEP committee`.

DEP (not a DEP process) should be managed by the DEP author and only the the flow processing should be managed by the DEP committee.

Or a DEP committee want a real monocracy?

**Comment by NDxTreme** [comment]
Of course the DEP is managed by the DEP committee. The name of the committee tells you what it manages. Most committee's start out named that way, in English at least. ( I cannot speak for any other languages, not knowing any other than English.)

Dart is not a democracy. Dart is a language specification. That specification is managed by the ECMA TC 52 group. Its very nature is not democratic. Democracy is every person to vote on an issue. 

A Republic, like the United States, elects officials to vote for them. Therefore, Dart is also not a Republic.

It follows that a committee cannot grant democratic or republic standing from such a structure. They can promote ideas similar to them, however, and that is what the DEP is all about.

Let anyone come up with an idea, flesh it out, then pick the best of the lot. This process is managed by the DEP committee, whose purpose is to figure this stuff out.

They just started, so their plans are facing the long standing reality that generals know well. "No plan survives first contact with the enemy."
