### ISSUE TITLE
Spaceship Operator

### ISSUE THREAD

**Issue by kaendfinger** [dart-lang/dart_enhancement_proposals#25]
[Proposal](https://github.com/DirectMyFile/dep-spaceship/blob/master/proposal.md)

@munificent This one should be just about ready, let me know what needs to be improved :)

**Comment by sethladd** [comment]
I miss this from Ruby.

**Comment by kaendfinger** [comment]
It's very useful, even though it's super small.

**Comment by munificent** [comment]
This looks detailed enough to me for the committee to take a look. We aren't meeting again until after the summit but if you'd like use to take a look at it then, I'm up for it.

**Comment by kaendfinger** [comment]
@munificent I would love for you guys to take a look at it :)

**Comment by munificent** [comment]
I really appreciate you writing this up, and I think you did a great job writing a clean and simple proposal. Unfortunately, we don't think it's a good fit for Dart. The [meeting notes](https://github.com/dart-lang/dart_enhancement_proposals/blob/master/Meetings/2015-05-06%20DEP%20Committee%20Meeting.md) have more details on why.

**Comment by kaendfinger** [comment]
Thanks for at least considering it :)
