### ISSUE TITLE
clarification about patent rights

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/dart_enhancement_proposals#27]
When I first read the DEP template, I saw this section on patent rights near the end:

https://github.com/dart-lang/dart_enhancement_proposals/blob/master/DEP%20Template.md#patents-rights

Is this a section that needs to be included explicitly on each DEP? As it is written, it seemed a piece of information for a DEP author, but not necessarily a section that needs to be included on every proposal. I have however seen several proposals that include it.

It might be worth clarifying or making the distinction more explicitly in the template. If this is a note for the author, maybe it should move to the instructions or the walkthrough?

**Comment by munificent** [comment]
I'm honestly not sure what the right answer is to this. @anders-sandholm?

**Comment by anders-sandholm** [comment]
It is more of a "PLEASE NOTE" to the author rather than something that should be included in the DEP itself. It is also part of the instructions already - albeit with fewer words. I'll delete the section and add more wording to the instructions.

**Comment by anders-sandholm** [comment]
resolved with https://github.com/dart-lang/dart_enhancement_proposals/pull/46
