### ISSUE TITLE
Let static analysis allow calls on values of type Function.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/dart_enhancement_proposals#28]
I've created a proposal for a small change to the static type system: 
https://github.com/lrhn/dep-functiontype/blob/master/proposal.md
It will allow existing (currently warning-causing) code to become valid instead of fixing the implementations and breaking the code. 

I've made a post to core-dev, and initial responses have been positive.

**Comment by eernstg** [comment]
Nice!

On Tue, Apr 21, 2015 at 4:34 PM, lrhn <notifications@github.com> wrote:

> I've created a proposal for a small change to the static type system:
> https://github.com/lrhn/dep-functiontype/blob/master/proposal.md
> It will allow existing (currently warning-causing) code to become valid
> instead of fixing the implementations and breaking the code.
>
> I've made a post to core-dev, and initial responses have been positive.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dart-lang/dart_enhancement_proposals/issues/28>.
>



-- 
Erik Ernst  -  Google Danmark ApS
Skt Petri Passage 5, 2 sal, 1165 København K, Denmark
CVR no. 28866984
