### ISSUE TITLE
README doesn't specify if there's a naming requirement for DEP filenames

### ISSUE THREAD

**Issue by sethladd** [dart-lang/dart_enhancement_proposals#36]
Not sure if it matters, but maybe there's a convention for the actual DEP file names. e.g. `dep___.md` ?

**Comment by sethladd** [comment]
Looks like `proposal.md` is the way to go.

**Comment by sethladd** [comment]
If that's correct, I'll send a PR for the DEP's readme. Please let me know. Thanks!

**Comment by munificent** [comment]
Yeah, that's right. Send me a fix!

**Comment by sethladd** [comment]
https://github.com/dart-lang/dart_enhancement_proposals/pull/38

**Comment by munificent** [comment]
I don't think it really matters much.
