### ISSUE TITLE
Assert with optional message

### ISSUE THREAD

**Issue by sethladd** [dart-lang/dart_enhancement_proposals#37]
I think my proposal is far enough along to start getting the committee's time on it. It lives [here](https://github.com/sethladd/dep_assert_with_optional_message/blob/master/proposal.md).

_Note: This issue is a tracking bug for the status of the proposal. To comment on the proposal itself, file issues on its repo, not here._

**Comment by sethladd** [comment]
@gbracha drafted a version of the spec with the specifics for this feature. Will try to link here.

**Comment by sethladd** [comment]
Implementors have reported feedback:

https://github.com/dart-lang/sdk/issues/24216#issuecomment-144940784

https://github.com/dart-lang/sdk/issues/24216#issuecomment-144826202

https://github.com/dart-lang/sdk/issues/24216#issuecomment-144593695

**Comment by lrhn** [comment]
This feature has been added to the language since the DEP process was abandoned.
