### ISSUE TITLE
Metaclasses

### ISSUE THREAD

**Issue by gbracha** [dart-lang/dart_enhancement_proposals#4]
This is a proposal to endow Type objects with type-specific behavior, effectively creating a distinct metaclass for each class. This will make classes behave as first class runtime values.

Repository: https://github.com/gbracha/metaclasses

**Comment by danschultz** [comment]
@polux there's subscribe button over on the right.

**Comment by sethladd** [comment]
Can we discuss this proposal in one of the next DEP meetings? We have a customer that would love use this feature, if available. Thanks!

**Comment by munificent** [comment]
> We have a customer that would love use this feature, if available.

Can they provide some details on what they want to use it for?

**Comment by sethladd** [comment]
cc @hixie

**Comment by munificent** [comment]
Note that the right place to provide feedback isn't on this issue. Either email [core-dev@](https://groups.google.com/a/dartlang.org/forum/#!forum/core-dev) or file issues on the [proposal's repo](https://github.com/gbracha/metaclasses).

**Comment by sethladd** [comment]
Should we just lock the issue? I've seen others be confused about all the different places one can leave a comment.

**Comment by Hixie** [comment]
Metaclasses are the main pain point I have in dealing with Dart in the context of developing extensible platforms, i.e. platforms where core features get extended post-hoc. In particular I miss:

- the ability to define types whose range is a class and its subclasses

For example:

```dart
   abstract class LayoutManager { ... }
   void registerLayoutManager(Class<LayoutManager> manager, String name) { ... }
```
...where `registerLayoutManager()`'s first argument has to be a subclass of `LayoutManager` (or indeed `LayoutManager` itself, if it wasn't abstract).

- the ability to call static methods, static fields, and constructors on class types

For example:

```dart
   class Foo {
     Foo() { print("constructor"); }
     static String get name => 'my-name';
     static void test() => print('foo');
   }
   void main() {
     var X = Foo;
     Foo f = new X(); // prints "constructor"
     print(X.name); // prints "my-name"
   }
```

- virtual static methods and virtual static fields

```dart
   // assume Foo from above exists
   class Bar extends Foo {
     @override static String get name => 'bar';
     @override void test() { print('bar'); super.test(); }
   }
   void register(Class<Foo> x) {
     print("going to register ${x.name}");
   }
   void main() {
     Foo X = Bar;
     X.test(); // prints "bar" then "foo";
     register(X); // prints "going to register bar"
     register(Foo); // prints "going to register my-name"
   }
```

- virtual constructors

The above are all useful, but really virtual constructors are the most important:

```dart
   abstract class Element {
     constructor();
     // no idea what the right syntax should be to distinguish virtual
     // constructors from regular constructors, but I guess we need
     // something since Dart didn't start with inherited constructors.
     // since they're virtual presumably they wouldn't be named after
     // the class either. But the details don't matter.
     static String get tagName;
     // ...
   }
   class FooElement extends Element {
     @override constructor();
     @override static String get tagName => 'foo';
   }
   class BarElement extends Element {
     @override constructor();
     @override static String get tagName => 'bar';
   }
   Map<String, Class<Element>> registrations = {};
   registerElement(Class<Element> e) {
     registrations[e.tagName] = e;
   }
   instantiateElement(String tagName) {
     return new registrations[tagName]();
   }
```

**Comment by lrhn** [comment]
The DEP process has been discontinued, so closing this issue.
Any new discussion about metaclasses should happen in the [language repo](https://github.com/dart-lang/language/).
