### ISSUE TITLE
Interface libraries

### ISSUE THREAD

**Issue by munificent** [dart-lang/dart_enhancement_proposals#40]
This is yet another proposal for handling configuration-specific code in Dart. The repo lives here:

https://github.com/munificent/dep-interface-libraries

_Note: This issue is a tracking bug for the status of the proposal. To comment on the proposal itself, file issues on its repo, not here._

**Comment by munificent** [comment]
We have a working implementation of this behind a flag now.

**Comment by lrhn** [comment]
Closing this for now, as we have no current plans to do this. 
If we need the link, we can add it to the [language](https://github.com/dart-lang/language) repo.
