### ISSUE TITLE
Right Hand Types

### ISSUE THREAD

**Issue by emilniklas** [dart-lang/dart_enhancement_proposals#42]
I know how preposterous this DEP is, but I wrote it out, and it lives [here](https://github.com/emilniklas/dep-right-hand-types/blob/master/proposal.md).

**Comment by kasperpeulen** [comment]
nice! I would like to see this being considered for Dart 2.0

However I feel like Swift's `->` arrows for return type are a bit easier to read:

```dart
callMultipleZ(functions: Iterable<StringManipulator>) -> Iterable<String> {
  return functions.map((f: StringManipulator) => f('z'));
}
```

then having this overkill of colons:
```dart
callMultipleZ(functions: Iterable<StringManipulator>): Iterable<String> {
  return functions.map((f: StringManipulator) => f('z'));
}
```

**Comment by emilniklas** [comment]
@kasperpeulen makes a good point, I think. For the record, TypeScript does this:

```typescript
function x(functionArgument: (T) => T): T { ... }
```

Colon for return types, but `=>` for return types in type declarations. I don't particularly like it, though.

**Comment by lrhn** [comment]
The Go language has postfix types with not separator. That would be:

    callMultupleZ(function Iterable<StringManipulator>) Itearable<String> {  ... }

That's probably too confusing a change since it's using almost the same syntax as the current language but with the opposite order.

**Comment by emilniklas** [comment]
@lrhn Hmm... If we don't introduce some sort of punctuation, expressing function signature expressions gets (even more) confusing, I think:

```dart
m(a T, f (T) T) (T) T
// as opposed to something like
m(a: T, f: (T) -> T): (T) -> T
```

**Comment by emilniklas** [comment]
@lrhn Can you maybe give some insight on this?: emilniklas/dep-right-hand-types#1

**Comment by emilniklas** [comment]
@kasperpeulen I've done some digging and thinking and it seems like `->` is a really nice way to do it.

Since this whole discussion exists because of higher order functions and that we're entering the realm of functional programming here, I checked out some conventions from that world, and it seems colon syntax is standard, as well as `→` for return types. This makes a lot of sense since the following semantics apply:

```dart
: // "is a"
-> // "turns into"

name: String // "name is a string"
triple: Int -> Int // "triple is a function where an integer is turned into another integer"
```

Also, with arrows, we don't have to supply as many parentheses:

```dart
f: ((T): T) // parens galore!
f: (T: T) // argument list with argument T of type T?
f: (T): T // plain confusing
f: T -> T // clear functional syntax
f: (T, T) -> T // multiple arguments
f: T, T -> T // too far?
```

**Comment by emilniklas** [comment]
Another use case that popped up. Optionals in type expression:

```dart
f: (T, U, V, [X], {named: Y}) -> RT // way too complex...?
```

**Comment by emilniklas** [comment]
And another:

```dart
// Dart today
typedef ReturnType MyTypeDef(Type thisNameIsNeverEverRelevant);

// With ONLY proposed right hand syntax
typedef MyTypeDef(thisNameIsNeverEverRelevant: Type) -> ReturnType;

// Without excessive names
typedef MyTypeDef(Type) -> ReturnType;

// If typedefs were to follow higher order function arguments from proposal
typedef MyTypeDef: (Type) -> ReturnType;
// This would allow for type aliasing
typedef SimpleMap: Map<String, dynamic>
// Maybe introduce typedef generics? Getting complex now...
typedef SimpleMap<T>: Map<String, T>
```

**Comment by Cat-sushi** [comment]
I'm looking forward to the acceptance of this proposal, but I can't suppose how can we get there.
What do you think the migration strategy like [that of NNBD](https://github.com/chalin/DEP-non-null/blob/master/doc/dep-non-null-AUTOGENERATED-DO-NOT-EDIT.md#part-migration "DEP-non-null/dep-non-null-AUTOGENERATED-DO-NOT-EDIT.md at master · chalin/DEP-non-null") is?
In some steps of migration, how can the compiler switch parsers?
Otherwise, should the parser be able to parse right hand types and left hand types at the same time?
I prefer the latte one, because dart makes much account of syntactic similarity to C and Java.

BTW, [`:` as a separator of default values of named parameters](http://news.dartlang.org/2016/12/dart-121-generic-method-syntax.html "Dart News & Updates: Dart 1.21: Generic Method Syntax") is ready to be deprecated, now!

**Comment by eernstg** [comment]
You're sliding away from the topic implied by the title (and I don't think types to the right are coming anytime soon), but for function type syntax you may wish to take a look at [this issue](https://github.com/dart-lang/sdk/issues/27527) and [this document](https://gist.github.com/eernstg/ffc7bd281974e9018f10f0cb6cfee4aa).

**Comment by Cat-sushi** [comment]
Me?
I had already read the docs @eernstg referred, but I'm not talking about generic functions.
I referred [Dart News & Updates: Dart 1.21: Generic Method Syntax](http://news.dartlang.org/2016/12/dart-121-generic-method-syntax.html "Dart News & Updates: Dart 1.21: Generic Method Syntax") for its second topic of "default value for a named argument" related to [here](https://github.com/emilniklas/dep-right-hand-types/blob/master/proposal.md#with-named-parameters "dep-right-hand-types/proposal.md at master · emilniklas/dep-right-hand-types")

**Comment by eernstg** [comment]
I was referring to the function type subtopic (so I guess I should have addressed @emilniklas and @kasperpeulen explicitly). The new function type syntax allows for generic methods as well as non-generic ones, in a typedef and inline in a declaration, and that seems to be relevant for several of the comments above.

**Comment by Cat-sushi** [comment]
Probably, I have understood.
But, I prefer this proposal because of readability, consistency, generality, and so on.
And this proposal also covers non-function types.
At the same time, I think I understand the difficulty of this proposal, and it is the reason why I'm asking some migration strategy.

**Comment by lrhn** [comment]
The DEP process has been replaced, and language proposals now happen in the https://github.com/dart-lang/language/ report. 
If anyone is still interested in right hand types, the proposal can be reposted there, but there are no current plans to go forward with something that is both this wide-reaching and still mainly cosmetic.
(In other words, the odds are low that this will happen, unless we choose to do a complete syntax rewamp at some point - say a Dart X.0 which is not source compatible with Dart X-1.0, so compilers will need two parsers).
