### ISSUE TITLE
member interceptors

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/dart_enhancement_proposals#44]
I realize now that I never created an entry for the member interceptors DEP:

https://github.com/sigmundch/DEP-member-interceptors/issues

The DEP hasn't changed in the past year, but it will help to put an entry here to keep track of any decisions or status of the proposal.

My understanding of the current status is on hold. Others have put interest in creating a more comprehensive proposal for macros, rather than the specialized member-interceptors described on the DEP.

**Comment by munificent** [comment]
This feature has a lot of complexity, and after some discussion, we don't plan to invest work into it, at least not right now.
