### ISSUE TITLE
Resolved Part-Of directives

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/dart_enhancement_proposals#45]
Now that library names are optional, this is even more useful as a way to declare part-of directives without using a library directive in the first place.

https://github.com/sigmundch/DEP-resolved-part-of/blob/master/proposal.md

**Comment by lrhn** [comment]
+1. We should do this for Dart 1.0, ASAP.

We should also reconsider our modularity design for Dart 2.0 and see if we can come up with something better, preferably where "part files" are not just textually included, but where they can have local declarations or imports that do not affect the library they are parted into.
Or something smarter.

**Comment by lrhn** [comment]
Dart now supports "resolved part-of directives" like `part of "library.dart";` for libraries with no names.
We don't (yet) support abbreviations. If we do, they may or may not be useful for part-of directives.
