### ISSUE TITLE
The fromMicrosecondsSinceEpoch function of DateTime class is not working properly 

### ISSUE THREAD

**Issue by disburden** [dart-lang/dart_enhancement_proposals#49]
DateTime dd = new DateTime.fromMicrosecondsSinceEpoch(1527310817);
      print("date:$dd");

No matter how the parameters change, the displayed results are always the same
flutter: date:1970-01-01 08:25:17.310817
flutter: date:1970-01-01 08:25:17.310817

(dart 2.0)

**Comment by floitschG** [comment]
This issue was moved to dart-lang/sdk#33262
