### ISSUE TITLE
Package spec file

### ISSUE THREAD

**Issue by munificent** [dart-lang/dart_enhancement_proposals#5]
@lrhn has a DEP for specifying how packages are located using an explicit mapping file instead of a "packages" directory.

Repo: https://github.com/lrhn/dep-pkgspec

**Note: This issue is for tracking the *status* of the proposal. If you would like to provide feedback on the proposal itself, please do so by filing issues on [its repo](https://github.com/lrhn/dep-pkgspec).**

**Comment by zoechi** [comment]
Absolute paths (including /home/someuser/...) don't look to good and won't work well with CVS. 
Some environment variable interpolation could solve this. 

Seems this file has to be maintained in addition to pubsec. yaml, at least when manual entries are made.

**Comment by munificent** [comment]
> Absolute paths (including /home/someuser/...) don't look to good and won't work well with CVS. 

You wouldn't check this file into source control. (That's what the lock file is for.)

> Seems this file has to be maintained in addition to pubsec. yaml, at least when manual entries are made.

Pub will create it for you. It's exactly analogous to the "packages" directory full of symlinks that pub currently generates for you.

**Comment by zoechi** [comment]
Thanks, I got it.
I wondered if there is more into it because manual entries were explicitly mentioned in the proposal.

**Comment by sethladd** [comment]
Hi, who are we awaiting revision from? And what's a good way for me to see what revisions/updates we are waiting for?

Thanks!

**Comment by sethladd** [comment]
Friendly ping. How can I tell what the open issues are, that need to be addressed?

**Comment by sethladd** [comment]
Never mind, figured it out.

**Comment by iposva-google** [comment]
The proposal at https://github.com/lrhn/dep-pkgspec at commit be26d503e495b115e302d722d124423372af21b3 looks good to me.

I am planning to implement the handling of the packages.map handling in the standalone VM within the next two weeks.

**Comment by jmesserly** [comment]
fyi, permalink to that revision: https://github.com/lrhn/dep-pkgspec/blob/be26d503e495b115e302d722d124423372af21b3/DEP-pkgspec.md

(apparently you can press "y" to get that. TIL. https://help.github.com/articles/getting-permanent-links-to-files/)

**Comment by sethladd** [comment]
For tracking: here's the meta issue collecting all the implementation issues in one spot: https://code.google.com/p/dart/issues/detail?id=23372

**Comment by sethladd** [comment]
We've closed out all outstanding issues over at https://github.com/lrhn/dep-pkgspec/issues. Please take another look. Thanks!

**Comment by munificent** [comment]
It's accepted! I'll send out my DEP meeting notes when I get a chance with some more details.

**Comment by sethladd** [comment]
Very cool, thank you!
