### ISSUE TITLE
Null-aware operators

### ISSUE THREAD

**Issue by munificent** [dart-lang/dart_enhancement_proposals#9]
Author: @gbracha
Repo: https://github.com/gbracha/nullAwareOperators

**Note: If you have feedback on this proposal, please provide at the linked repo and not on this issue.**

**Comment by munificent** [comment]
This is now accepted and on its way to TC52! :ship:

**Comment by nex3** [comment]
Isn't an implementation required before a DEP is accepted?

**Comment by munificent** [comment]
In this case, the summary basically fully describes the semantics. In general, I think we should soften the language around how "necessary" an implementation is.

**Comment by nex3** [comment]
I agree that the semantics are clear, but it's nice to be able to concretely use a feature before sending it off to TC52. For this one in particular it's so similar to features in other languages that's less necessary, but in general it seems like a good step.

**Comment by munificent** [comment]
> I agree that the semantics are clear, but it's nice to be able to concretely use a feature before sending it off to TC52.

I agree. We're still shaking out the process but I also feel the first few DEPs went through very quickly. Hopefully over time we'll get to a mode where we spend more time battle-testing a proposal before it gets locked into the spec.

**Comment by sethladd** [comment]
From my understanding, the original DEP proposal is now out of date. If anyone is here looking for the definitive specification, check out https://codereview.chromium.org//1031323002

cc @stereotype441 @gbracha to confirm

**Comment by sethladd** [comment]
The 3rd edition of the Dart language specification now includes null-aware operators. Check it out here: https://www.dartlang.org/docs/spec/
